# Generated by Django 4.1.3 on 2022-12-15 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasties_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=16,
                                   unique=True,
                                   validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
